/* =========================================================
   DocumentGovernance.js
   Orchestrator for Version Control & Category Management
   ========================================================= */
window.SecurityUtils = {
    checkLoginStatus: () => {
        // Checks the DOM for the Profile or Sign out links generated by Power Pages
        const allLinks = Array.from(document.querySelectorAll('a'));
        const isLoggedIn = allLinks.some(a => {
            const text = a.innerText.trim().toLowerCase();
            return text === "profile" || text === "sign out";
        });

        if (!isLoggedIn) {
            SecurityUtils.showLoginModal();
            return false;
        }
        return true;
    },

    closeModal: () => {
        const modal = document.getElementById("loginModal");
        if (modal) modal.remove();
    },

    showLoginModal: () => {
        if (document.getElementById("loginModal")) return;

        const modalHtml = `
            <div id="loginModal" style="position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(15, 23, 42, 0.7); z-index:9999; display:flex; justify-content:center; align-items:center; backdrop-filter: blur(4px);">
              <div style="background:white; padding:40px; border-radius:12px; max-width:440px; text-align:center; position:relative; box-shadow: 0 10px 25px rgba(0,0,0,0.5);">
                
                <button id="dr-modal-close-x" style="position:absolute; top:15px; right:15px; border:none; background:none; font-size:20px; cursor:pointer; color:#999;">&times;</button>
                
                <i class="fa fa-lock" style="font-size: 48px; color: #004A99; margin-bottom: 20px;"></i>
                <h2 style="margin-top:0; font-family: ui-sans-serif, system-ui; font-weight: 800; color: #1E293B;">Session Expired</h2>
                <p style="color: #64748B; line-height: 1.5; font-family: ui-sans-serif, system-ui;">Dataverse information cannot be loaded while you are signed out.</p>
                
                <hr style="margin: 20px 0; border: 0; border-top: 1px solid #E2E8F0;">
                
                <p style="font-family: ui-sans-serif, system-ui; font-size: 14px;"><strong>Please sign back in via the link in the top right corner.</strong></p>
                
                <button id="dr-modal-got-it" style="margin-top: 20px; background-color: #004A99; color: #fff; border: none; padding: 12px 30px; border-radius: 6px; font-weight: 700; cursor: pointer; font-family: ui-sans-serif, system-ui;">
                    Got it
                </button>
              </div>
            </div>
          `;

        // 1. Add the HTML to the page
        document.body.insertAdjacentHTML('beforeend', modalHtml);

        // 2. Safely attach the click events (CSP Compliant)
        document.getElementById('dr-modal-close-x').addEventListener('click', SecurityUtils.closeModal);
        document.getElementById('dr-modal-got-it').addEventListener('click', SecurityUtils.closeModal);
    }
};

const DocumentApp = {
    state: {
        recordId: null,
        selectedCategoryId: null,
        selectedFileId: null,
        categories: [],
        history: []
    },

    // Add this block:
    renderSkeletons: function () {
        // Sidebar Category Skeletons
        const catSkeletons = Array(4).fill(0).map(() => `
                <div class="shimmer is-loading" style="width: 100%; height: 60px; border-radius: 12px; margin-bottom: 12px;"></div>
            `).join('');
        $('#category-sidebar').html(catSkeletons); // Ensure this ID matches your HTML

        // Document Card Skeletons
        const docSkeletons = Array(3).fill(0).map(() => `
                <div class="doc-file-card" style="display: flex; gap: 16px;">
                    <div class="shimmer is-loading" style="width: 40px; height: 40px; border-radius: 8px; flex-shrink: 0;"></div>
                    <div style="flex-grow: 1;">
                        <div class="shimmer is-loading" style="width: 60%; height: 18px; margin-bottom: 8px;"></div>
                        <div class="shimmer is-loading" style="width: 30%; height: 12px;"></div>
                    </div>
                    <div class="shimmer is-loading" style="width: 80px; height: 24px; border-radius: 6px;"></div>
                </div>
            `).join('');
        $('#file-list-container').html(docSkeletons); // Ensure this ID matches your HTML
    },

    fetchGlobalSettings: async function () {
        try {
            const table = window.SCHEMA.TABLES.GLOBAL_SETTINGS;
            const id = window.SCHEMA.FIELDS.GLOBAL_SETTINGS.RECORD_ID;
            const field = window.SCHEMA.FIELDS.GLOBAL_SETTINGS.MATRIX;

            // Note: We include the Anti-Forgery token just in case Power Pages requires it for this specific Web API endpoint
            const token = window.shell ? await new Promise(r => window.shell.getTokenDeferred().done(r).fail(() => r(''))) : $('input[name="__RequestVerificationToken"]').val();

            const response = await fetch(`/_api/${table}(${id})?$select=${field}`, {
                headers: {
                    'Accept': 'application/json',
                    '__RequestVerificationToken': token
                }
            });

            if (response.ok) {
                const data = await response.json();
                return data[field];
            }
        } catch (e) {
            console.error("Failed to load dynamic document matrix, falling back to defaults.", e);
        }
        return null;
    },

    init: async function (config) {
        console.log("🚀 Initializing Document Governance App...");

        // SHOW SKELETONS IMMEDIATELY
        this.renderSkeletons();

        // 1. Get the SharePoint ID from URL parameters
        const urlParams = new URLSearchParams(window.location.search);
        const spId = urlParams.get('id');

        if (!spId) {
            console.error("❌ No SharePoint ID provided. Returning to Board.");
            window.location.href = '/';
            return;
        }

        this.state.recordId = spId;

        // 2. Fetch the deal to check status AND commercial model
        try {
            const deal = await window.SubmissionService.getDealById(spId);
            if (deal) {
                this.state.dealStatus = parseInt(deal[window.SCHEMA.FIELDS.DEALS.STATUS]);
                this.state.commercialModel = parseInt(deal[window.SCHEMA.FIELDS.DEALS.COMMERCIAL_MODEL]);
            }
        } catch (e) {
            console.warn("Could not load deal status for lock check.");
        }

        // 3. Fetch the Global Settings Matrix
        this.state.matrixJSON = await this.fetchGlobalSettings();

        // 4. Initialize dynamic schema and load docs
        this.state.categories = this.buildCategorySchema();
        await this.loadDocuments();

        this.selectFirstPopulatedCategory();
        this.render();
    },

    buildCategorySchema: function () {
        let parsed = {};
        try { parsed = JSON.parse(this.state.matrixJSON || "{}"); } catch (e) { }

        // Fallback blueprint if the DB is empty
        const defaultDocTypes = [
            { id: "MSA", name: "Master Services Agreement" },
            { id: "SOW", name: "Statement of Work (SOW)" },
            { id: "PRICING", name: "Pricing / Cost Model" }
        ];

        const docTypes = (parsed.docTypes && Array.isArray(parsed.docTypes)) ? parsed.docTypes : defaultDocTypes;
        const rules = parsed.rules || parsed;

        // Map Dataverse Model Integers to the Matrix JSON Keys
        const modelMap = {
            0: "TM",
            1: "TM_NTE",
            2: "FIXED_FEE",
            3: "FIXED_CAP",
            4: "FIXED_FEE" // Fallback Retainer to Fixed Fee rules
        };
        const currentModelKey = modelMap[this.state.commercialModel] || "TM";

        const schema = [];

        docTypes.forEach(doc => {
            // Check what the admin set for this specific document and deal model
            const rule = (rules[doc.id] && rules[doc.id][currentModelKey]) || "Optional";

            // If the admin didn't mark it "Hidden", add it to the UI
            if (rule !== "Hidden") {
                schema.push({
                    id: doc.id.toLowerCase(), // lowercased to match existing logic
                    name: doc.name,
                    required: rule === "Required",
                    files: []
                });
            }
        });

        // Fallback safety net: if everything is hidden, force SOW to appear
        if (schema.length === 0) {
            schema.push({ id: 'sow', name: 'Statement of Work', required: true, files: [] });
        }

        return schema;
    },

    selectFirstPopulatedCategory: function () {
        // Find the first category in the schema that has at least one file
        const firstPopulated = this.state.categories.find(cat => cat.files && cat.files.length > 0);

        if (firstPopulated) {
            console.log(`🎯 Auto-selecting category: ${firstPopulated.name}`);
            this.state.selectedCategoryId = firstPopulated.id;
            this.autoSelectFile(); // Highlight the first file in that category
        } else {
            // Fallback to SOW if everything is empty
            this.state.selectedCategoryId = window.SCHEMA.DOC_CATEGORIES.SOW.id;
        }
    },

    autoSelectFile: function () {
        const cat = this.state.categories.find(c => c.id === this.state.selectedCategoryId);
        if (cat && cat.files.length > 0) {
            // Sort by uploadedDate descending (newest first)
            const sorted = [...cat.files].sort((a, b) => new Date(b.uploadedDate) - new Date(a.uploadedDate));
            this.state.selectedFileId = sorted[0].id;
        } else {
            this.state.selectedFileId = null;
        }
    },

    loadDocuments: async function () {
        this.state.categories = this.buildCategorySchema();
        const mode = (window.DR_CONFIG?.runtime?.mode || "mock").toLowerCase();

        if (mode === 'live') {
            // 1. Get the already-mapped files from the Service
            const rawFiles = await SubmissionService.loadDocumentsViaFlow(this.state.recordId);

            if (!Array.isArray(rawFiles)) return;

            this.state.categories.forEach(cat => {
                cat.files = rawFiles
                    .filter(file => file && this.isMatch(file, cat.id))
                    .map(file => {
                        // --- KEEP YOUR PATH EXTRACTION LOGIC ---
                        let path = "";
                        if (file.url) {
                            if (file.isExternalLink) {
                                path = file.url;
                            } else {
                                try {
                                    const urlObj = new URL(file.url);
                                    path = decodeURIComponent(urlObj.pathname);
                                } catch (e) {
                                    path = file.url;
                                }
                            }
                        }

                        // --- THE SURGERY: DON'T RE-CALCULATE NAME OR isExternalLink ---
                        // We trust what came from SubmissionService.mapFlowToState
                        return {
                            ...file,
                            fileRef: path,
                            // Use file.name and file.isExternalLink as they were mapped in the Service
                            uploadedDate: file.modifiedDate || file.uploadedDate || new Date().toLocaleDateString()
                        };
                    });
            });

            // --- AUTO-SELECT LOGIC ---
            const firstWithFiles = this.state.categories.find(c => c.files.length > 0);
            if (firstWithFiles) {
                this.state.selectedCategoryId = firstWithFiles.id;
                this.autoSelectFile();
            }
        } else {
            this.loadMockDocuments();
        }
    },

    isMatch: function (file, catId) {
        const targetId = (typeof catId === 'object' && catId !== null) ? catId.id : catId;
        const normalizedTarget = (targetId || "").toLowerCase();

        const flowCategory = (file.documentCategory || file.spCategory || file.category || "").toLowerCase();
        const fileName = (file.fileName || file.name || "").toLowerCase();

        // 1. Direct or Mapped Match
        const displayToIdMap = {
            'cost model': 'pricing',
            'statement of work': 'sow',
            'master agreement': 'msa'
        };

        if (flowCategory === normalizedTarget || displayToIdMap[flowCategory] === normalizedTarget) {
            return true;
        }

        // 2. Hardcoded Fallbacks for core docs
        const mapping = {
            'sow': ['sow'],
            'msa': ['msa'],
            'pricing': ['pricing', 'cost', 'estimate'],
            'rate': ['rate'],
            'arch': ['arch', 'diagram']
        };

        if (mapping[normalizedTarget] && mapping[normalizedTarget].some(term => fileName.includes(term))) {
            return true;
        }

        // 3. Dynamic Fallback for custom categories created in Admin UI
        // e.g., if the ID is "PROPOSAL_1234", it looks for "proposal" in the file name
        const dynamicTerm = normalizedTarget.split('_')[0];
        if (dynamicTerm && dynamicTerm.length > 3 && fileName.includes(dynamicTerm)) {
            return true;
        }

        return false;
    },

    loadMockDocuments: function () {
        const CATS = window.SCHEMA.DOC_CATEGORIES;
        const STATUS = window.SCHEMA.DOC_STATUS;

        const sowCat = this.state.categories.find(c => c.id === CATS.SOW);
        if (sowCat) {
            sowCat.files = [
                {
                    id: 'doc-101',
                    name: 'SOW_Project_Alpha_v1.pdf',
                    version: 1, size: '1.1 MB',
                    uploadedBy: 'Matthew Ranlett',
                    uploadedDate: '2026-02-10',
                    status: STATUS.ALIGNED
                },
                {
                    id: 'doc-102',
                    name: 'SOW_Project_Alpha_v2_Final.pdf',
                    version: 2, size: '1.4 MB',
                    uploadedBy: 'Kimberly Ranlett',
                    uploadedDate: '2026-02-18',
                    status: STATUS.ALIGNED
                }
            ];
        }
    },

    render: function () {
        const $mount = $('#document-governance-app');
        if (!$mount.length) return;

        $mount.html(DocumentUI.layout(this.state));
        this.bindEvents();
    },

    loadHistory: async function (fileId) {
        const STATUS = window.SCHEMA.DOC_STATUS;

        // 1. Loading State
        DocumentUI.showToast("Fetching SharePoint Version History...");

        if (window.DR_CONFIG && window.DR_CONFIG.runtime.mode === 'live') {
            // 2. Fetch from your new helper Flow via SubmissionService
            this.state.history = await SubmissionService.loadFileHistory(fileId);
        } else {
            // Mock Data for local testing
            this.state.history = [
                { version: "3.0", modifiedDate: "Feb 18, 2026 2:14 PM", modifiedBy: "Kimberly Ranlett", size: "", note: "Final legal review applied.", status: STATUS.ALIGNED },
                { version: "2.0", modifiedDate: "Feb 15, 2026 10:45 AM", modifiedBy: "Matthew Ranlett", size: "", note: "Updated commercial terms.", status: STATUS.MODIFIED_SUBMISSION },
                { version: "1.0", modifiedDate: "Feb 10, 2026 9:00 AM", modifiedBy: "Matthew Ranlett", size: "", note: "Initial upload.", status: STATUS.ALIGNED }
            ];
        }

        // 3. Re-render the UI to display the history in the Timeline
        this.render();
    },

    bindEvents: function () {
        const self = this;
        const C = DocumentUI.CONSTANTS;

        // 1. Category Selection
        $('.doc-cat-btn').off('click').on('click', function () {
            self.state.selectedCategoryId = $(this).data('id');
            self.state.history = []; // Reset history view on category change
            self.autoSelectFile();
            self.render();
        });

        // 2. File Selection (Highlighting and Timeline Context)
        $('.doc-file-card').off('click').on('click', function () {
            self.state.selectedFileId = $(this).data('file-id');
            self.state.history = []; // Reset history when switching file focus
            self.render();
        });

        // 3. Navigation
        $(document).off('click', '#btn-back-to-board, .btn-back-to-deal').on('click', '#btn-back-to-board, .btn-back-to-deal', (e) => {
            e.preventDefault(); // Stop standard navigation
            e.stopPropagation();
            window.location.href = `/new-submission/?id=${this.state.recordId}`;
        });

        // 4. Action Handlers
        $(`.${C.BTN_UPLOAD}`).off('click').on('click', (e) => { e.stopPropagation(); this.handleUpload(); });

        $('.btn-download').off('click').on('click', (e) => {
            e.stopPropagation();
            const id = $(e.currentTarget).data('id');
            const file = self.state.categories.flatMap(c => c.files).find(f => f.id == id);

            if (file && file.isExternalLink) {
                window.open(file.fileRef, '_blank'); // Open the Estimator
            } else {
                this.handleDownload(id); // Download the Doc
            }
        });

        $('.btn-delete').off('click').on('click', (e) => { e.stopPropagation(); this.handleDelete($(e.currentTarget).data('id')); });

        // 5. Run Manual AI Pre-Check (With Loading State)
        $(document).off('click', '.btn-run-ai').on('click', '.btn-run-ai', async (e) => {
            e.preventDefault();
            e.stopPropagation();

            const $btn = $(e.currentTarget);
            const fileId = $btn.data('id');
            const originalHtml = $btn.html(); // Save the exact original HTML

            // --- UI LOADING STATE ---
            // Safely update the HTML while forcing the browser to render the spinner
            $btn.html('<i class="fa fa-spinner fa-spin mr-1" style="animation: fa-spin 1s infinite linear;"></i> Analyzing...')
                .css({ 'pointer-events': 'none', 'opacity': '0.7', 'cursor': 'wait' });

            DocumentUI.showToast("AI is analyzing the document...");

            try {
                // Call the Power Automate Flow
                const success = await window.SubmissionService.runAIAudit(fileId, self.state.recordId);

                if (success) {
                    DocumentUI.showToast("AI Scan Complete! Refreshing data...", "success");
                    await self.loadDocuments();
                    self.render();
                } else {
                    throw new Error("Flow failed");
                }
            } catch (error) {
                DocumentUI.showToast("AI Scan Failed.", "error");
                // Reset the button exactly as it was
                $btn.html(originalHtml).css({ 'pointer-events': 'auto', 'opacity': '1', 'cursor': 'pointer' });
            }
        });

        // View History Click
        $('.btn-history').off('click').on('click', function (e) {
            e.stopPropagation();
            const fileId = $(this).data('id');
            self.loadHistory(fileId);
        });

        $('.btn-download-version').off('click').on('click', function (e) {
            e.stopPropagation();
            const versionId = $(this).data('version-id');

            const selectedCat = self.state.categories.find(c => c.id === self.state.selectedCategoryId);
            const selectedFile = selectedCat ? selectedCat.files.find(f => f.id === self.state.selectedFileId) : null;

            if (selectedFile && selectedFile.fileRef && versionId) {
                // Direct call for better popup handling in Chrome
                SubmissionService.downloadHistoryVersion(selectedFile.fileRef, versionId, selectedFile.name);
            } else {
                DocumentUI.showToast("Could not resolve version path.", "error");
            }
        });

        /***
         * Add 3Ci Estimator Link (modal with screen overlay)
         */
        // 1. Show the Modal
        $(document).off('click', '#btn-add-estimator-link').on('click', '#btn-add-estimator-link', function () {
            const cat = self.state.categories.find(c => c.id === self.state.selectedCategoryId);

            // Clean up any old modal instances
            $('#linkModal').remove();
            $('.modal-backdrop').remove();

            const modalHtml = DocumentUI.renderLinkModal(cat.name);
            $('body').append(modalHtml);

            const $modal = $('#linkModal');
            $modal.modal({ backdrop: 'static', keyboard: false });
            $modal.modal('show');

            $modal.on('shown.bs.modal', function () {
                $('#modal-link-url').trigger('focus');
            });
        });

        // 2. Handle the "Save Link" button inside the modal
        $(document).off('click', '#btn-confirm-link').on('click', '#btn-confirm-link', async function () {
            const url = $('#modal-link-url').val();
            const title = $('#modal-link-title').val();

            if (!url || !title) {
                DocumentUI.showToast("Please provide both a URL and a Title", "error");
                return;
            }

            DocumentUI.showProcessingOverlay("Saving Estimator Link...");

            const success = await SubmissionService.saveEstimatorLink(
                self.state.recordId,
                self.state.selectedCategoryId,
                url,
                title
            );

            if (success) {
                $('#linkModal').modal('hide');

                // 1. Pull the new data from SharePoint
                await self.loadDocuments();

                // 2. TRICK: Re-render the WHOLE app so the Left Nav count updates
                self.state.selectedCategoryId = self.state.selectedCategoryId;
                self.render();

                DocumentUI.hideProcessingOverlay(true);
                DocumentUI.showToast("Link saved successfully!");
            } else {
                DocumentUI.hideProcessingOverlay(false);
                DocumentUI.showToast("Failed to save link.", "error");
            }
        });

        /***  
         * Side Panel functionality
        */
        // 1. Open Side Panel
        $(document).off('click', '.btn-open-ai-panel').on('click', '.btn-open-ai-panel', function () {
            const fileId = $(this).data('id');
            const file = self.state.categories.flatMap(c => c.files).find(f => f.id == fileId);

            if (file) {
                $('#ai-scorecard-panel').html(DocumentUI.renderAIScorecard(file)).addClass('is-open');
                $('#ai-scorecard-overlay').fadeIn(200);
            }
        });

        // 2. Close Side Panel
        $(document).off('click', '#close-ai-panel, #ai-scorecard-overlay').on('click', '#close-ai-panel, #ai-scorecard-overlay', function () {
            $('#ai-scorecard-panel').removeClass('is-open');
            $('#ai-scorecard-overlay').fadeOut(200);
        });

        // UI Interaction: Toggle Mandatory Text Boxes
        $(document).off('change', '.mandatory-action-rad').on('change', '.mandatory-action-rad', function () {
            const card = $(this).closest('.mandatory-card');
            if ($(this).val() === 'fix') {
                card.find('.justification-container').slideUp(200);
                card.find('.fix-container').slideDown(200);
            } else {
                card.find('.fix-container').slideUp(200);
                card.find('.justification-container').slideDown(200);
            }
        });

        // Save AI Justifications
        $(document).off('click', '#btn-save-ai-feedback').on('click', '#btn-save-ai-feedback', async function () {
            const fileId = $(this).data('id');
            const $btn = $(this);

            let pendingOverrides = [];
            let missingJustification = false;

            // Only scrape Mandatory cards where the user chose "Justify"
            $('.mandatory-card').each(function () {
                const action = $(this).find('.mandatory-action-rad:checked').val();
                if (action === 'justify') {
                    const val = $(this).find('.mandatory-justification-input').val().trim();
                    const standard = $(this).data('standard');

                    if (val === '') {
                        missingJustification = true;
                        $(this).find('.mandatory-justification-input').css({ 'border-color': '#DC2626', 'background': '#FEF2F2' });
                    } else {
                        $(this).find('.mandatory-justification-input').css({ 'border-color': '#FCD34D', 'background': '#FFF' });
                        pendingOverrides.push({ standardName: standard, justification: val });
                    }
                }
            });

            if (missingJustification) {
                DocumentUI.showToast("Please provide a justification for all selected Mandatory findings.", "error");
                return;
            }

            $btn.html('<i class="fa fa-spinner fa-spin mr-2"></i> Saving...').css('pointer-events', 'none');

            // Send to Dataverse via SubmissionService
            const success = await SubmissionService.saveRepOverrides(fileId, self.state.recordId, pendingOverrides);

            if (success) {
                DocumentUI.showToast("Resolutions Saved");
                $('#ai-scorecard-panel').removeClass('is-open');
                $('#ai-scorecard-overlay').fadeOut(200);
                await self.loadDocuments();
                self.render();
            } else {
                DocumentUI.showToast("Error saving resolutions", "error");
                $btn.html('<i class="fa fa-save mr-2"></i> Save AI Resolutions').css('pointer-events', 'auto');
            }
        });
        /*** end side panel */
    },

    /***
     * Document File Handlers - CRUD functions
     */
    handleUpload: function () {
        const self = this;
        const selectedCat = this.state.categories.find(c => c.id === this.state.selectedCategoryId);

        // 1. Ensure the container exists and inject HTML
        if (!$('#upload-modal-container').length) $('body').append('<div id="upload-modal-container"></div>');
        $('#upload-modal-container').html(DocumentUI.renderUploadModal(selectedCat.name));

        // 2. Show Modal using jQuery syntax (more compatible with older/wrapped Bootstrap)
        const $modal = $('#uploadModal');
        $modal.modal('show');

        // 3. Auto-fill title when file is picked
        $('#modal-file-input').on('change', function () {
            const fileName = this.files[0]?.name || "";
            $('#modal-title-input').val(fileName);
        });

        // 4. Handle the 'Start Upload' click
        $('#btn-confirm-upload').off('click').on('click', async function () {
            const file = $('#modal-file-input')[0].files[0];
            const metadata = {
                title: $('#modal-title-input').val(),
                versionTag: $('#modal-tag-input').val() || "Manual Upload",
                category: self.state.selectedCategoryId
            };

            if (!file) {
                DocumentUI.showToast("Please select a file first", "error");
                return;
            }

            // 1. Lock the Modal Button
            $(this).prop('disabled', true);

            // 2. Hide Modal and Show Global Shield
            $modal.modal('hide');
            DocumentUI.showProcessingOverlay(`Uploading ${file.name}...`);

            // 3. Perform the Upload
            const success = await SubmissionService.uploadDocument(file, metadata);

            // 4. Release the Shield and Refresh
            DocumentUI.hideProcessingOverlay();

            if (success) {
                DocumentUI.showToast("Upload Successful!");
                await self.loadDocuments();
                self.render();
            } else {
                DocumentUI.showToast("Upload failed. Check Power Automate history.", "error");
                // Optionally re-show the modal if it fails
                $(this).prop('disabled', false);
            }
        });
    },

    handleDownload: function (id) {
        // 1. Find the file object in our current state using the ID
        let foundFile = null;
        this.state.categories.forEach(cat => {
            const file = cat.files.find(f => f.id == id);
            if (file) foundFile = file;
        });

        if (foundFile && foundFile.url) {
            DocumentUI.showToast(`Downloading ${foundFile.name}...`);

            // 2. Open the SharePoint URL in a new tab to trigger the download/view
            window.open(foundFile.url, '_blank');
        } else {
            DocumentUI.showToast("Download failed: File URL not found", "error");
        }
    },

    handleDelete: async function (id) {
        const confirmDelete = confirm("Are you sure you want to move this document to the SharePoint Recycle Bin?");
        if (!confirmDelete) return;

        DocumentUI.showToast("Deleting document...", "warning");

        try {
            // We'll add this method to SubmissionService next
            const success = await SubmissionService.deleteDocument(id);

            if (success) {
                DocumentUI.showToast("Document deleted successfully");
                // Refresh the list to show the file is gone
                await this.loadDocuments();
                this.render();
            }
        } catch (error) {
            DocumentUI.showToast("Delete failed", "error");
        }
    },

    handleViewHistory: async function (fileId) {
        console.log(`📜 Loading history for File ID: ${fileId}`);

        // 1. Fetch from your new flow
        const history = await SubmissionService.loadFileHistory(fileId);

        // 2. Pass to your UI renderer (e.g., a Modal or expanded row)
        this.renderHistoryModal(history);
    }
};

/**
 * DocumentUI.js
 * UI Rendering Engine for Document Governance
 * Modularized for maintainability and design system consistency.
 */
const DocumentUI = {
    /**
     * DOM IDs and Selectors to avoid magic strings
     */
    CONSTANTS: {
        WRAPPER: 'document-governance-app-wrapper',
        MOUNT: 'document-governance-app',
        FILE_LIST: 'file-list-container',
        BTN_BACK: 'btn-back-to-deal',
        BTN_UPLOAD: 'btn-upload-doc'
    },

    /**
     * 1. Main Orchestrator
     * Adjusted to ensure the header stays within the same max-width as the body 
     * for a cohesive look on ultra-wide screens.
     */
    layout: function (state) {
        const selectedCat = state.categories.find(c => c.id === state.selectedCategoryId);
        const selectedFile = selectedCat ? selectedCat.files.find(f => f.id === state.selectedFileId) : null;

        return `
        <div id="${this.CONSTANTS.WRAPPER}" class="dr-layout-wrapper">
            ${this.renderHeader(state)}
            
            <div class="dr-main-grid">
                ${this.renderLeftNav(state)}
                ${this.renderWorkPane(selectedCat, state.selectedFileId, selectedFile, state.history)}
            </div>
            
            <div id="ai-scorecard-overlay" class="panel-overlay"></div>
            <div id="ai-scorecard-panel" class="ai-panel"></div>
        </div>
        `;
    },

    /**
     * 2. Header Block
     * Handles titles and global actions.
     */
    renderHeader: function (state) {
        return `
            <header class="bg-white border-b dr-header-wrapper">
                <div class="dr-container-inner">
                    <div class="py-6 d-flex align-items-center justify-content-between w-100">
                        <div class="header-title-group">
                            <a href="javascript:void(0);" id="${this.CONSTANTS.BTN_BACK}" class="d-inline-flex align-items-center mb-1 text-muted text-decoration-none btn-back-to-deal" style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; gap: 5px;">
                                <i class="fa fa-arrow-left"></i> Back to Deal
                            </a>
                            <h1 class="text-2xl font-bold mb-1 text-primary" style="margin: 0; line-height: 1.2;">
                                Document Governance
                            </h1>
                            <p class="text-sm text-muted mb-0 font-medium">
                                Structured Document Management & Version Control
                            </p>
                        </div>
                        <div class="header-actions"></div>
                    </div>
                </div>
            </header>
        `;
    },

    /**
     * 3. Left Navigation Block
     * Renders the list of document types and the progress bar.
     */
    renderLeftNav: function (state) {
        const requiredCats = state.categories.filter(c => c.required);
        const totalRequired = requiredCats.length;
        const metRequired = requiredCats.filter(c => c.files && c.files.length > 0).length;
        const progressPercent = totalRequired === 0 ? 100 : (metRequired / totalRequired) * 100;
        const barColor = progressPercent === 100 ? 'var(--state-success)' : '#B45309';

        const progressHtml = `
            <div class="mt-6 pt-4 border-t">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="text-xs font-bold text-muted text-uppercase" style="letter-spacing: 1px; font-size: 10px;">Required Progress</span>
                    <span class="text-sm font-bold" style="color: ${barColor};">${metRequired}/${totalRequired}</span>
                </div>
                <div class="dr-progress-container-v3">
                    <div class="dr-progress-bar-v3" style="width: ${progressPercent}%; background-color: ${barColor};"></div>
                </div>
                ${progressPercent === 100 ? `<p class="text-xs text-success mt-2 mb-0 font-bold"><i class="fa fa-check-circle mr-1"></i> All required documents uploaded</p>` : ''}
            </div>
        `;

        return `
            <aside class="sidebar-rail bg-white border-r d-flex flex-column dr-sidebar-nav">
                <div class="dr-label-xs mb-6 ms-2">DOCUMENT CATEGORIES</div>
                <nav class="d-flex flex-column gap-3 flex-grow-1">
                    ${state.categories.map(cat => this.renderCategoryButton(cat, state.selectedCategoryId)).join('')}
                </nav>
                ${progressHtml}
            </aside>
        `;
    },

    /**
     * 4. Right 'Work' Pane Block
     * The dynamic area for document management.
     */
    renderWorkPane: function (category, selectedFileId, selectedFile, history) {
        if (!category) return `<div class="flex-grow-1 p-10 text-center text-muted">Select a category to begin.</div>`;

        return `
        <main class="flex-grow-1 py-8 px-12 overflow-y-auto dr-work-pane">
            <div class="work-pane-content dr-work-pane-content">
                ${this.renderWorkPaneHeader(category)}
                
                <section id="${this.CONSTANTS.FILE_LIST}">
                    ${category.files.length === 0 ? this.renderEmptyState(category) : this.renderFileList(category.files, selectedFileId)}
                </section>
                
                ${this.renderTimeline(selectedFile ? selectedFile.name : null, history)}
            </div>
        </main>
        `;
    },

    /**
     * --- UI COMPONENTS (Sub-modules) ---
     */

    renderCategoryButton: function (cat, selectedId) {
        const isActive = cat.id === selectedId;
        const activeClass = isActive ? 'is-active' : '';
        const hasFiles = cat.files && cat.files.length > 0;

        const borderStyle = isActive
            ? 'border: 2px solid var(--brand-primary);'
            : 'border: 1px solid var(--border-default);';

        // Dynamic Badge Logic
        let badgeHtml = '';
        if (cat.required) {
            if (!hasFiles) {
                badgeHtml = `<span style="background: #FEE2E2; color: #B91C1C; padding: 2px 6px; border-radius: 4px; font-weight: 800; font-size: 9px; margin-left: 8px; letter-spacing: 0.5px;">REQUIRED</span>`;
            } else {
                badgeHtml = `<span style="background: #D1F0D8; color: #1E7E34; padding: 2px 6px; border-radius: 4px; font-weight: 800; font-size: 9px; margin-left: 8px; letter-spacing: 0.5px;"><i class="fa fa-check mr-1"></i>MET</span>`;
            }
        } else {
            badgeHtml = `<span style="background: #F1F5F9; color: #64748B; padding: 2px 6px; border-radius: 4px; font-weight: 800; font-size: 9px; margin-left: 8px; letter-spacing: 0.5px;">OPTIONAL</span>`;
        }

        return `
            <button class="doc-cat-btn ${activeClass} transition-all" 
                    data-id="${cat.id}" 
                    style="${borderStyle} width: 100%; display: block; padding: 16px; border-radius: var(--radius-md); background: #fff;">
                
                <div class="d-flex align-items-center justify-content-between mb-2">
                    <span class="cat-name font-bold text-primary" style="font-size: 14px; text-align: left;">${cat.name}</span>
                    <i class="fa fa-file-text-o ${isActive ? 'brand-text' : 'text-muted'}" style="font-size: 15px;"></i>
                </div>
                
                <div class="d-flex align-items-center gap-2">
                    <span class="text-xs text-muted" style="font-weight: 500;">
                        ${cat.files.length} ${cat.files.length === 1 ? 'file' : 'files'}
                    </span>
                    ${badgeHtml}
                </div>
            </button>
        `;
    },

    renderWorkPaneHeader: function (cat) {
        // Safely grab the state from the global app instance
        const appState = window.DocumentGovernanceApp.state;
        const isLocked = appState.dealStatus === window.SCHEMA.CHOICES.STATUS.APPROVED || appState.dealStatus === window.SCHEMA.CHOICES.STATUS.SUBMITTED;

        return `
            <div class="d-flex align-items-center justify-content-between mb-8">
                <div>
                    <h2 class="font-bold text-medium" style="color: var(--text-primary); margin:0;">${cat.name}</h2>
                    <p class="text-sm text-muted mb-0">${cat.required ? 'Required Category' : 'Optional Category'}</p>
                </div>
                <div class="d-flex gap-3">
                    <button class="dr-btn-secondary px-4 d-flex align-items-center gap-2" id="btn-add-estimator-link" style="${isLocked ? 'display: none !important;' : ''}">
                        <i class="fa fa-calculator" style="font-size: 14px;"></i> 
                        <span>Add Estimator Link</span>
                    </button>
                    
                    <button class="btn-submission btn-submit ${this.CONSTANTS.BTN_UPLOAD}" style="opacity: 1; ${isLocked ? 'display: none !important;' : ''}">
                        <i class="fa fa-upload mr-2"></i> Upload Document
                    </button>
                </div>
            </div>
        `;
    },

    renderEmptyState: function (cat) {
        return `
            <div class="doc-empty-state">
                <i class="fa fa-file-upload fa-3x text-muted mb-4" style="opacity: 0.3;"></i>
                <h3 class="font-medium text-lg">No documents uploaded</h3>
                <p class="text-sm text-muted mb-6">
                    ${cat.required ? 'This is a required category. Please upload at least one document.' : 'Upload supporting documents for this category.'}
                </p>
                <button class="btn-submission btn-submit ${this.CONSTANTS.BTN_UPLOAD}" style="opacity: 1;">Upload First Document</button>
            </div>
        `;
    },

    renderFileList: function (files, selectedFileId) {
        if (!files || !Array.isArray(files)) return '';
        return `<div class="space-y-4">
            ${files.map(file => file ? this.renderFileCard(file, file.id === selectedFileId) : '').join('')}
        </div>`;
    },

    renderFileCard: function (file, isSelected) {
        const selectedClass = isSelected ? 'is-selected' : '';
        const sizeDisplay = file.size ? `<span>•</span> <span>${file.size}</span>` : '';
        const docIcon = file.isExternalLink ? 'fa-calculator text-info' : 'fa-file-pdf-o';
        const appState = window.DocumentGovernanceApp.state;
        const isLocked = appState.dealStatus === window.SCHEMA.CHOICES.STATUS.APPROVED || appState.dealStatus === window.SCHEMA.CHOICES.STATUS.SUBMITTED;

        const healthScore = file.healthScore || "Pending";
        let theme = { color: '#475569', bg: '#F1F5F9', icon: 'fa-clock-o', text: 'Pending AI Scan' };

        if (healthScore === "Clean") {
            theme = { color: '#1E7E34', bg: '#D1F0D8', icon: 'fa-check-circle', text: 'AI Score: Clean' };
        } else if (healthScore === "Warning") {
            theme = { color: '#B45309', bg: '#FEF3C7', icon: 'fa-exclamation-triangle', text: 'AI Score: Warning' };
        } else if (healthScore === "Critical Risk") {
            theme = { color: '#B91C1C', bg: '#FEE2E2', icon: 'fa-times-circle', text: 'AI Score: Critical Risk' };
        }

        const isSowCategory = file.documentCategory === 'sow';
        const aiAllowed = !file.isExternalLink && isSowCategory;
        const isDocx = file.name && file.name.toLowerCase().endsWith('.docx');

        let aiBadgeHtml = '';
        if (aiAllowed) {
            const safeTooltip = String(file.aiSummary || theme.text).replace(/"/g, '&quot;');
            aiBadgeHtml = `<span class="dr-badge-status" data-tooltip="${safeTooltip}" style="background: ${theme.bg}; color: ${theme.color};">
                    <i class="fa ${theme.icon} mr-1"></i> ${theme.text}
                </span>`;
        }

        const hasFindings = file.aiFindings && file.aiFindings.trim() !== "" && file.aiFindings.trim().toLowerCase() !== "none";
        const calloutText = hasFindings ? "AI detected specific findings for review." : "AI analysis complete. No deviations found.";

        const auditLogBlock = (healthScore !== "Pending" && !file.isExternalLink) ? `
            <div class="dr-ai-callout" style="background: ${theme.bg}; border-left: 4px solid ${theme.color};">
                <div class="dr-ai-callout-text" style="color: ${theme.color};"><i class="fa ${theme.icon} mr-1"></i> ${calloutText}</div>
                <button class="btn-open-ai-panel dr-ai-callout-btn" data-id="${file.id}" style="color: ${theme.color};">View Scorecard</button>
            </div>
        ` : '';

        let aiButtonHtml = '';
        if (aiAllowed) {
            if (isDocx) {
                const btnText = (healthScore === "Pending") ? "Run AI Audit" : "Re-Scan Document";
                const btnIcon = (healthScore === "Pending") ? "fa-microchip" : "fa-refresh";
                aiButtonHtml = `<button class="btn-run-ai dr-btn-secondary btn-sm dr-btn-ai-action" data-id="${file.id}" style="${isLocked ? 'display: none !important;' : ''}">
                    <i class="fa ${btnIcon} mr-1"></i> ${btnText}
                </button>`;
            } else {
                aiButtonHtml = `<button class="dr-btn-secondary btn-sm dr-btn-ai-disabled" disabled title="AI scanning requires a .docx file" style="${isLocked ? 'display: none !important;' : ''}">
                    <i class="fa fa-file-word-o mr-1"></i> Requires .docx
                </button>`;
            }
        }

        const fileUrl = file.url || file.fileRef || '#';
        const workflowStateDisplay = file.workflowState || 'Draft';
        const workflowColor = workflowStateDisplay === 'Draft' ? '#64748B' : (workflowStateDisplay === 'Approved' ? '#1E7E34' : '#2563EB');

        return `
            <div class="dr-file-card transition-all ${selectedClass}" data-file-id="${file.id}">
                <div class="d-flex align-items-start justify-content-between">
                    <div class="d-flex align-items-center gap-3">
                        <div class="dr-doc-icon-box"><i class="fa ${docIcon}"></i></div>
                        <div>
                            <h4 class="font-bold mb-0">
                                <a href="${fileUrl}" target="_blank" class="dr-file-title-link">${file.name}</a>
                            </h4>
                            <div class="d-flex align-items-center gap-2 text-xs text-muted" style="margin-top: 2px; font-weight: 500;">
                                <span class="${file.isExternalLink ? 'text-info font-bold' : ''}">${file.isExternalLink ? '3Ci Estimator' : `v${file.version}`}</span>
                                ${sizeDisplay} <span>•</span> <span>${file.uploadedBy}</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="d-flex align-items-center gap-2" style="flex-shrink: 0;">
                        ${aiButtonHtml}
                        <button class="dr-btn-secondary btn-sm btn-download" data-id="${file.id}" title="${file.isExternalLink ? 'Open Estimator' : 'Download'}"><i class="fa ${file.isExternalLink ? 'fa-external-link' : 'fa-download'}"></i></button>
                        <button class="dr-btn-secondary btn-sm text-danger btn-delete" data-id="${file.id}" title="Delete" style="${isLocked ? 'display: none !important;' : ''}"><i class="fa fa-trash"></i></button>
                    </div>
                </div>
                
                ${auditLogBlock}

                <div class="mt-3 pt-3 border-t d-flex align-items-center justify-content-between" style="border-color: var(--border-default);">
                    <div class="d-flex align-items-center gap-3">
                        ${aiBadgeHtml}
                        <span class="font-bold" style="color: ${workflowColor}; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;">
                            <i class="fa fa-code-fork mr-1"></i> ${workflowStateDisplay}
                        </span>
                    </div>
                    ${!file.isExternalLink ? `
                        <button class="text-xs brand-text font-bold hover:underline bg-transparent border-0 btn-history" data-id="${file.id}">
                            <i class="fa fa-history mr-1"></i> View History
                        </button>
                    ` : '<span class="text-xs text-muted"><i class="fa fa-link mr-1"></i> External</span>'}
                </div>
            </div>
        `;
    },

    renderTimeline: function (selectedFileName, history = []) {
        const title = selectedFileName ? `TIMELINE: ${selectedFileName}` : 'DOCUMENT TIMELINE';

        return `
            <div class="dr-timeline-container">
                <div class="dr-label-xs mb-4">${title}</div>
                ${history.length > 0 ? this.renderHistoryList(history) : this.renderTimelineEmptyState(selectedFileName)}
            </div>
        `;
    },

    renderHistoryList: function (history) {
        return `
        <div class="dr-history-list space-y-4">
            ${history.map((item) => {
            const hScore = item.healthScore || "Pending";
            let badgeColor = '#64748B'; let badgeIcon = 'fa-clock-o'; let badgeLabel = 'Pending AI';

            if (hScore === "Clean") { badgeColor = '#1E7E34'; badgeIcon = 'fa-check-circle'; badgeLabel = 'Clean'; }
            else if (hScore === "Warning") { badgeColor = '#B45309'; badgeIcon = 'fa-exclamation-triangle'; badgeLabel = 'Warning'; }
            else if (hScore === "Critical Risk") { badgeColor = '#B91C1C'; badgeIcon = 'fa-times-circle'; badgeLabel = 'Critical Risk'; }

            const displayNote = item.note || "No version tag provided";

            const auditLogHtml = item.aiSummary
                ? `<div class="dr-history-audit" style="border-left: 3px solid ${badgeColor};"><strong>AI Audit:</strong> ${item.aiSummary}</div>`
                : '';

            return `
                    <div class="dr-history-item d-flex gap-3">
                        <div style="min-width: 54px;">
                            <button class="btn-download-version dr-version-pill" data-version-id="${item.versionId}" title="Download this version">
                                <span>v${item.version}</span> <i class="fa fa-download superscript-dl-icon" style="font-size: 8px;"></i>
                            </button>
                        </div>
                        
                        <div class="flex-grow-1">
                            <div class="dr-history-meta">
                                <span class="dr-history-author">${item.modifiedBy}</span>
                                <span class="dr-history-date">${item.modifiedDate}</span>
                            </div>
                            
                            <div class="dr-history-note">"${displayNote}"</div>

                            <div class="d-flex align-items-center gap-3">
                                <div class="dr-history-badge" style="color: ${badgeColor};"><i class="fa ${badgeIcon} mr-1"></i> ${badgeLabel}</div>
                                <span class="text-xs text-muted" style="font-size: 10px;">• State: ${item.workflowState || 'Draft'}</span>
                            </div>
                            ${auditLogHtml}
                        </div>
                    </div>
                `;
        }).join('')}
        </div>
        `;
    },

    renderTimelineEmptyState: function (selectedFileName) {
        return `
            <div class="timeline-empty-card">
                <div class="timeline-icon-wrapper"><i class="fa fa-history"></i></div>
                <p class="timeline-placeholder-text">
                    ${selectedFileName
                ? `Select 'View History' on a file to see the audit trail for ${selectedFileName}.`
                : `Select a document to view its version history and approval audit trail.`}
                </p>
            </div>
        `;
    },

    renderLinkModal: function (categoryName) {
        return `
        <div class="modal fade" id="linkModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: var(--radius-lg); border: none;">
                    <div class="modal-header border-0 pt-6 px-6">
                        <h5 class="modal-title font-bold">Add 3Ci Estimator Link</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body px-6">
                        
                        <div class="mb-4 p-3 d-flex gap-3" style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-left: 4px solid var(--brand-primary); border-radius: 6px;">
                            <i class="fa fa-calculator mt-1" style="color: var(--brand-primary); font-size: 16px;"></i>
                            <div style="font-size: 13px; color: #475569; line-height: 1.5;">
                                <strong style="color: var(--text-primary); display: block; margin-bottom: 2px;">Instructions</strong>
                                Please use the 3Ci Estimator to model one or more scenarios for this deal. You can generate a link to paste below by accessing the tool here:
                                <div class="mt-2">
                                    <a href="https://3ci-estimator.powerappsportals.com/" target="_blank" style="color: var(--brand-primary); font-weight: 700; text-decoration: none;">
                                        Launch 3Ci Estimator <i class="fa fa-external-link ms-1" style="font-size: 10px;"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="mb-4">
                            <label class="dr-label-xs mb-2">ESTIMATOR URL</label>
                            <input type="text" id="modal-link-url" class="form-control" placeholder="https://3ci-estimator.../?estimateId=...">
                        </div>
                        <div class="mb-4">
                            <label class="dr-label-xs mb-2">MODEL TITLE</label>
                            <input type="text" id="modal-link-title" class="form-control" placeholder="e.g. Q3 Managed Services Model">
                        </div>
                    </div>
                    <div class="modal-footer border-0 pb-6 px-6">
                        <button type="button" class="dr-btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="button" id="btn-confirm-link" class="btn-submission btn-submit" 
                            style="background-color: #0078d4 !important; color: white !important; opacity: 1 !important; cursor: pointer !important; pointer-events: auto !important;">
                            <i class="fa fa-link mr-2"></i> Save Link
                        </button>
                    </div>
                </div>
            </div>
        </div>`;
    },

    showToast: function (message, type = 'success') {
        if (!$('#toast-container').length) $('body').append('<div id="toast-container"></div>');
        const id = `toast-${Date.now()}`;
        const color = type === 'success' ? 'var(--state-success)' : 'var(--state-risk)';
        $('#toast-container').append(`
            <div id="${id}" class="dr-toast" style="background:${color}; color:white; padding:12px 24px; border-radius:8px; margin-bottom:10px; box-shadow:var(--shadow-md);">
                <span>${message}</span>
            </div>
        `);
        setTimeout(() => $(`#${id}`).fadeOut(() => $(`#${id}`).remove()), 3000);
    },

    renderUploadModal: function (categoryName) {
        return `
        <div class="modal fade" id="uploadModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: var(--radius-lg); border: none; shadow: var(--shadow-lg);">
                    <div class="modal-header border-0 pt-6 px-6">
                        <h5 class="modal-title font-bold">Upload to ${categoryName}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body px-6">
                        <div class="mb-4">
                            <label class="dr-label-xs mb-2">SELECT FILE</label>
                            <input type="file" id="modal-file-input" class="form-control form-control-sm">
                        </div>
                        <div class="mb-4">
                            <label class="dr-label-xs mb-2">DOCUMENT TITLE</label>
                            <input type="text" id="modal-title-input" class="form-control" placeholder="e.g. Project Alpha SOW">
                        </div>
                        <div class="mb-4">
                            <label class="dr-label-xs mb-2">VERSION TAG (COMMENTS)</label>
                            <textarea id="modal-tag-input" class="form-control" rows="2" placeholder="Describe this version..."></textarea>
                        </div>
                    </div>
                    <div class="modal-footer border-0 pb-6 px-6">
                        <button type="button" class="dr-btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="button" id="btn-confirm-upload" class="btn-submission btn-submit" 
                            style="background-color: #0078d4 !important; opacity: 1 !important; cursor: pointer !important;">
                            <i class="fa fa-cloud-upload mr-2"></i> Start Upload
                        </button>
                    </div>
                </div>
            </div>
        </div>`;
    },

    showProcessingOverlay: function (message = "Processing...") {
        if ($('#processing-shield').length) return;

        $('body').append(`
            <div id="processing-shield" style="
                position: fixed; top: 0; left: 0; width: 100vw; height: 100vh;
                background: rgba(255, 255, 255, 0.8); backdrop-filter: blur(4px);
                display: flex; flex-direction: column; align-items: center; justify-content: center;
                z-index: 9999; cursor: wait;">
                <div class="spinner-border text-primary mb-3" role="status" style="width: 3rem; height: 3rem;"></div>
                <h4 class="font-bold text-primary">${message}</h4>
                <p class="text-muted text-sm">Please do not refresh or close this tab.</p>
            </div>
        `);
    },

    hideProcessingOverlay: function (isSuccess = true) {
        const $shield = $('#processing-shield');
        if (!$shield.length) return;

        if (isSuccess) {
            $shield.find('.spinner-border').replaceWith('<i class="fa fa-check-circle fa-3x text-success mb-3"></i>');
            $shield.find('h4').text('Upload Complete!');
            setTimeout(() => {
                $shield.fadeOut(200, function () { $(this).remove(); });
            }, 800);
        } else {
            $shield.remove();
        }
    },

    getStatusUIConfig: function (statusKey) {
        const STATUS = window.SCHEMA.DOC_STATUS;
        const configs = {
            [STATUS.ALIGNED]: { label: 'Aligned', icon: 'fa-check-circle', class: 'status-aligned' },
            [STATUS.MODIFIED_SUBMISSION]: { label: 'Modified Since Submission', icon: 'fa-exclamation-triangle', class: 'status-warning' },
            [STATUS.MODIFIED_APPROVAL]: { label: 'Modified Since Approval', icon: 'fa-history', class: 'status-risk' },
            [STATUS.MISSING]: { label: 'Missing Required File', icon: 'fa-times-circle', class: 'status-risk' }
        };
        return configs[statusKey] || configs[STATUS.ALIGNED];
    },

    renderAIScorecard: function (file) {
        const health = file.healthScore || "Pending";
        const summaryText = file.aiSummary || "Review pending. The AI will audit commercial terms against the Deal Board metadata.";

        let findings = [];
        let isLegacyText = false;
        try {
            findings = typeof file.aiFindings === 'string' ? JSON.parse(file.aiFindings) : (file.aiFindings || []);
            if (!Array.isArray(findings)) isLegacyText = true;
        } catch (e) { isLegacyText = true; }

        if (isLegacyText) {
            return this._renderLegacyScorecard(file, health, summaryText); 
        }

        const critical = findings.filter(f => f.requirementLevel === 'Critical');
        const mandatory = findings.filter(f => f.requirementLevel === 'Mandatory');
        const optional = findings.filter(f => f.requirementLevel === 'Optional');

        const renderCriticalCard = (f) => `
            <div class="ai-card-critical">
                <div class="d-flex justify-content-between align-items-start mb-2">
                    <strong style="color: #991B1B; font-size: 14px;">${f.standardName}</strong>
                    <span class="ai-badge-critical">Critical</span>
                </div>
                <p class="ai-text-critical">${f.explanation}</p>
                <div class="ai-fix-banner"><i class="fa fa-ban mr-1"></i> Action Required: Document must be fixed and rescanned</div>
            </div>`;

        const renderMandatoryCard = (f, index) => {
            const radName = `rad_man_${index}`;
            return `
            <div class="mandatory-card ai-card-mandatory" data-standard="${f.standardName}">
                <div class="d-flex justify-content-between align-items-start mb-2">
                    <strong style="color: #92400E; font-size: 14px;">${f.standardName}</strong>
                    <span class="ai-badge-mandatory">Mandatory</span>
                </div>
                <p class="ai-text-mandatory">${f.explanation}</p>
                
                <div class="mb-2 d-flex gap-3">
                    <label class="text-xs" style="color: #92400E; font-weight: 600; cursor:pointer;">
                        <input type="radio" name="${radName}" value="justify" class="mandatory-action-rad" checked style="margin-right:4px;"> Provide Justification
                    </label>
                    <label class="text-xs" style="color: #92400E; font-weight: 600; cursor:pointer;">
                        <input type="radio" name="${radName}" value="fix" class="mandatory-action-rad" style="margin-right:4px;"> Commit to Fix
                    </label>
                </div>
                
                <div class="justification-container">
                    <textarea class="form-control mandatory-justification-input ai-justification-input" rows="2" 
                        placeholder="Why is this deviation acceptable for this deal?..."></textarea>
                </div>
                <div class="fix-container ai-fix-info" style="display:none;">
                    <i class="fa fa-info-circle mr-1"></i> Upload a corrected document to clear this finding.
                </div>
            </div>`;
        };

        const renderOptionalCard = (f, index) => {
            const radName = `rad_opt_${index}`;
            return `
            <div class="optional-card ai-card-optional">
                <div class="d-flex justify-content-between align-items-start mb-2">
                    <strong style="color: #1E293B; font-size: 14px;">${f.standardName}</strong>
                    <span class="ai-badge-optional">Optional</span>
                </div>
                <p class="ai-text-optional">${f.explanation}</p>
                
                <div class="d-flex gap-3">
                    <label class="text-xs" style="color: #334155; font-weight: 600; cursor:pointer;">
                        <input type="radio" name="${radName}" value="skip" checked style="margin-right:4px;"> Acknowledge / Skip
                    </label>
                    <label class="text-xs" style="color: #334155; font-weight: 600; cursor:pointer;">
                        <input type="radio" name="${radName}" value="fix" style="margin-right:4px;"> Commit to Fix
                    </label>
                </div>
            </div>`;
        };

        return `
            <div class="ai-panel-header">
                <div class="d-flex justify-content-between align-items-center">
                    <h3 class="font-bold mb-0 text-primary" style="font-size: 18px;">AI Resolution Stack</h3>
                    <button id="close-ai-panel" class="bg-transparent border-0 text-muted p-2"><i class="fa fa-times fa-lg"></i></button>
                </div>
            </div>

            <div class="ai-panel-body ai-panel-scroll-body">
                <div class="mb-4 p-3 bg-light rounded border">
                    <h4 class="font-bold text-sm mb-1">${file.name}</h4>
                    <p class="text-xs text-muted mb-0">${summaryText}</p>
                </div>

                ${findings.length === 0 ? `<div class="text-center p-5"><i class="fa fa-check-circle fa-3x text-success mb-3"></i><h4 class="font-bold text-success">Perfect Alignment</h4><p class="text-muted text-sm">No deviations from standards were found.</p></div>` : ''}

                ${critical.length > 0 ? `<div class="mb-4"><div class="ai-stack-title text-danger">Critical Blockers (${critical.length})</div>${critical.map(renderCriticalCard).join('')}</div>` : ''}
                ${mandatory.length > 0 ? `<div class="mb-4"><div class="ai-stack-title text-warning">Required Justifications (${mandatory.length})</div>${mandatory.map(renderMandatoryCard).join('')}</div>` : ''}
                ${optional.length > 0 ? `<div class="mb-4"><div class="ai-stack-title text-info">Warnings & Best Practices (${optional.length})</div>${optional.map(renderOptionalCard).join('')}</div>` : ''}
            </div>

            <div class="ai-panel-footer">
                ${critical.length > 0 ? `<div class="mb-3 text-xs font-bold text-danger"><i class="fa fa-exclamation-triangle mr-1"></i> Deal submission is blocked until Critical issues are fixed, but you may save draft justifications below.</div>` : ''}
                <button id="btn-save-ai-feedback" data-id="${file.id}" class="btn-submission w-100 py-3 btn-submit" style="border-radius: 8px;">
                    <i class="fa fa-save mr-2"></i> Save AI Resolutions
                </button>
            </div>
        `;
    },
};

// Map to global window for init call in HTML
window.DocumentGovernanceApp = DocumentApp;