/* =========================================================
   ReviewBoard.js - Deal Review Board Meeting Support
   Architecture: Modular Singleton
   ========================================================= */
window.SecurityUtils = {
    checkLoginStatus: () => {
        // Checks the DOM for the Profile or Sign out links generated by Power Pages
        const allLinks = Array.from(document.querySelectorAll('a'));
        const isLoggedIn = allLinks.some(a => {
            const text = a.innerText.trim().toLowerCase();
            return text === "profile" || text === "sign out";
        });

        if (!isLoggedIn) {
            SecurityUtils.showLoginModal();
            return false;
        }
        return true;
    },

    closeModal: () => {
        const modal = document.getElementById("loginModal");
        if (modal) modal.remove(); 
    },

    showLoginModal: () => {
        if (document.getElementById("loginModal")) return;

        const modalHtml = `
            <div id="loginModal" style="position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(15, 23, 42, 0.7); z-index:9999; display:flex; justify-content:center; align-items:center; backdrop-filter: blur(4px);">
              <div style="background:white; padding:40px; border-radius:12px; max-width:440px; text-align:center; position:relative; box-shadow: 0 10px 25px rgba(0,0,0,0.5);">
                
                <button id="dr-modal-close-x" style="position:absolute; top:15px; right:15px; border:none; background:none; font-size:20px; cursor:pointer; color:#999;">&times;</button>
                
                <i class="fa fa-lock" style="font-size: 48px; color: #004A99; margin-bottom: 20px;"></i>
                <h2 style="margin-top:0; font-family: ui-sans-serif, system-ui; font-weight: 800; color: #1E293B;">Session Expired</h2>
                <p style="color: #64748B; line-height: 1.5; font-family: ui-sans-serif, system-ui;">Dataverse information cannot be loaded while you are signed out.</p>
                
                <hr style="margin: 20px 0; border: 0; border-top: 1px solid #E2E8F0;">
                
                <p style="font-family: ui-sans-serif, system-ui; font-size: 14px;"><strong>Please sign back in via the link in the top right corner.</strong></p>
                
                <button id="dr-modal-got-it" style="margin-top: 20px; background-color: #004A99; color: #fff; border: none; padding: 12px 30px; border-radius: 6px; font-weight: 700; cursor: pointer; font-family: ui-sans-serif, system-ui;">
                    Got it
                </button>
              </div>
            </div>
          `;
          
        // 1. Add the HTML to the page
        document.body.insertAdjacentHTML('beforeend', modalHtml);
        
        // 2. Safely attach the click events (CSP Compliant)
        document.getElementById('dr-modal-close-x').addEventListener('click', SecurityUtils.closeModal);
        document.getElementById('dr-modal-got-it').addEventListener('click', SecurityUtils.closeModal);
    }
};

window.ImpactTracker = {
    currentDealId: null,
    currentDecision: null, // Added to track if it was an Approve or Reject
    selectedImpacts: [],

    showModal: function(dealId, decisionType) {
        this.currentDealId = dealId;
        this.currentDecision = decisionType; 
        this.selectedImpacts = [];

        const existing = document.getElementById('dr-impact-modal-container');
        if (existing) existing.remove();

        const html = `
            <div id="dr-impact-modal-container" class="impact-overlay">
                <div class="impact-modal">
                    <div class="impact-header">
                        <h3>Decision Logged Successfully</h3>
                        <p>Did this review cycle catch anything material?</p>
                    </div>
                    <div class="impact-body">
                        <div class="impact-chip-grid" id="dr-chip-grid">
                            <button class="impact-chip" data-val="Legal Risk Avoided">🛡️ Legal Risk</button>
                            <button class="impact-chip" data-val="Margin Saved">💵 Margin Saved</button>
                            <button class="impact-chip" data-val="Scope Clarified">🎯 Scope Clarified</button>
                            <button class="impact-chip" data-val="Rate Correction">📈 Rate Correction</button>
                        </div>
                        
                        <div class="impact-details" id="dr-impact-details">
                            <div class="grid-2-col" style="gap: 16px; margin-bottom: 16px;">
                                <div>
                                    <label style="font-size: 12px; font-weight: 700; color: var(--text-muted); margin-bottom: 4px; display: block;">Est. Value Saved ($)</label>
                                    <input type="number" id="dr-impact-value" class="dr-input" placeholder="e.g. 15000">
                                </div>
                                <div>
                                    <label style="font-size: 12px; font-weight: 700; color: var(--text-muted); margin-bottom: 4px; display: block;">Quick Note (Optional)</label>
                                    <input type="text" id="dr-impact-note" class="dr-input" placeholder="What was caught?">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="impact-actions">
                        <button class="dr-btn-secondary" id="btn-impact-skip">Skip</button>
                        <button class="btn-submit" id="btn-impact-save" style="opacity: 1;">Save Impact</button>
                    </div>
                </div>
            </div>
        `;

        document.body.insertAdjacentHTML('beforeend', html);
        setTimeout(() => { document.getElementById('dr-impact-modal-container').classList.add('is-visible'); }, 10);
        this.attachEvents();
    },

    attachEvents: function() {
        const self = this;
        document.querySelectorAll('.impact-chip').forEach(chip => {
            chip.addEventListener('click', function() {
                this.classList.toggle('is-active');
                const val = this.getAttribute('data-val');
                if (this.classList.contains('is-active')) {
                    self.selectedImpacts.push(val);
                } else {
                    self.selectedImpacts = self.selectedImpacts.filter(i => i !== val);
                }
                const detailsBox = document.getElementById('dr-impact-details');
                if (self.selectedImpacts.length > 0) detailsBox.classList.add('is-open');
                else detailsBox.classList.remove('is-open');
            });
        });

        document.getElementById('btn-impact-skip').addEventListener('click', () => self.closeModal());
        document.getElementById('btn-impact-save').addEventListener('click', () => self.saveImpact());
    },

    saveImpact: async function() {
        const valueSaved = document.getElementById('dr-impact-value').value;
        const note = document.getElementById('dr-impact-note').value;
        const impacts = this.selectedImpacts.join('; ');

        const btn = document.getElementById('btn-impact-save');
        btn.innerHTML = '<i class="fa fa-spinner fa-spin"></i> Saving...';
        btn.style.opacity = '0.7';
        btn.style.pointerEvents = 'none';

        // USE CONSTANTS
        const T = window.SCHEMA.TABLES.DEAL_IMPACTS;
        const F = window.SCHEMA.FIELDS.DEAL_IMPACTS;

        const payload = {
            [F.IMPACT_ID]: `ROI-${Date.now().toString().slice(-6)}`, 
            [F.DECISION_TYPE]: String(this.currentDecision).toUpperCase(),
            [F.CATEGORIES]: impacts,
            [F.VALUE_SAVED]: parseFloat(valueSaved) || 0,
            [F.NOTES]: note || "",
            [F.DEAL_BINDING]: `/ci_dealses(${this.currentDealId})`
        };

        try {
            const token = $('input[name="__RequestVerificationToken"]').val() || '';
            const response = await fetch(`/_api/${T}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    '__RequestVerificationToken': token
                },
                body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error(await response.text());
            if (window.SubmissionUI && window.SubmissionUI.showToast) {
                window.SubmissionUI.showToast("Impact log saved successfully!", "success");
            }
        } catch (error) {
            console.error("Failed to save ROI Impact to Dataverse:", error);
        } finally {
            this.closeModal();
        }
    },

    closeModal: function() {
        const container = document.getElementById('dr-impact-modal-container');
        if (container) {
            container.classList.remove('is-visible');
            setTimeout(() => container.remove(), 300);
        }
    }
};

(function ($) {
    const ReviewBoardApp = {

        /* =========================================================
           1. STATE MANAGEMENT
           ========================================================= */
        state: {
            deals: [],              // Array of raw Dataverse Deal records
            selectedDealId: null,   // The GUID of the currently active tab
            uploadedDocs: [],       // SharePoint documents for the active deal
            history: [],            // Review history from SharePoint list via Dataverse
            isLoadingDocs: false,   // UI spinner toggle
            feedback: {             // Temporary hold for the user's review form
                decision: null,     // 'approve' | 'reject'
                notes: "",
                actionSummary: "",
                exceptionApproved: null // null | true | false
            }
        },

        /* =========================================================
           2. INITIALIZATION & LIFECYCLE
           ========================================================= */
        fetchGlobalSettings: async function() {
            try {
                const table = window.SCHEMA.TABLES.GLOBAL_SETTINGS;
                const id = window.SCHEMA.FIELDS.GLOBAL_SETTINGS.RECORD_ID;
                const token = window.shell ? await new Promise(r => window.shell.getTokenDeferred().done(r).fail(()=>r(''))) : $('input[name="__RequestVerificationToken"]').val();

                const response = await fetch(`/_api/${table}(${id})`, {
                    headers: { 'Accept': 'application/json', '__RequestVerificationToken': token }
                });
                
                if (response.ok) return await response.json();
            } catch (e) {
                console.error("Failed to load global settings, falling back to defaults.", e);
            }
            return null;
        },

        init: async function () {
            console.log("🚀 Launching Deal Review Board...");

            // SHOW SKELETONS IMMEDIATELY
            this.renderSkeletons();

            try {
                // 1. Fetch Global Admin Settings FIRST so SubmissionCalc has context
                window.model = window.model || {};
                window.model.globalSettings = await this.fetchGlobalSettings();

                // 2. Fetch Deals & Filter
                const rawDeals = await window.SubmissionService.loadAllDeals();
                this.state.deals = this.getReviewReadyDeals(rawDeals);

                // 3. Build the empty shell UI
                this.renderLayout();

                // 4. Check for URL deep link (from email) or load the first deal
                const urlParams = new URLSearchParams(window.location.search);
                const urlDealId = urlParams.get('dealId');
                const F = window.SCHEMA.FIELDS.DEALS;

                if (urlDealId && this.state.deals.some(d => d[F.DEALID] === urlDealId || String(d[F.EXTERNALKEY]) === urlDealId)) {
                    const targetDeal = this.state.deals.find(d => d[F.DEALID] === urlDealId || String(d[F.EXTERNALKEY]) === urlDealId);
                    await this.selectDeal(targetDeal[F.DEALID]);
                } else if (this.state.deals.length > 0) {
                    await this.selectDeal(this.state.deals[0][F.DEALID]);
                } else {
                    this.renderEmptyState();
                }

                this.bindEvents();

            } catch (err) {
                console.error("❌ Review Board Init Failed:", err);
                $('#review-board-app-wrapper').html(`<div class="alert alert-danger p-4 m-4">Failed to load the Review Board. Check console for details.</div>`);
            }
        },

        /* =========================================================
           3. DATA MANAGEMENT & LOGIC
           ========================================================= */
        getReviewReadyDeals: function (rawDeals) {
            const S = window.SCHEMA.CHOICES.STATUS;
            const F = window.SCHEMA.FIELDS.DEALS;

            return rawDeals
                .filter(d => d[F.STATUS] === S.SUBMITTED)
                .map(d => this.mapRawDealToState(d));
        },

        mapRawDealToState: function (d) {
            const F = window.SCHEMA.FIELDS.DEALS;
            const stats = window.SubmissionCalc ? window.SubmissionCalc.getGlobalProgress(d) : { percent: 0 };
            return {
                ...d,
                readinessScore: stats.percent,
                marginBand: this._calculateMarginBand(d[F.MARGIN])
            };
        },

        _calculateMarginBand: function (val) {
            const pct = (val || 0) * 100;
            
            // Pull dynamic Admin thresholds (fallback to 40/30 if API failed)
            const settings = window.model?.globalSettings || {};
            const target = settings[window.SCHEMA.FIELDS.GLOBAL_SETTINGS.TARGET_MARGIN] || 40;
            const critical = settings[window.SCHEMA.FIELDS.GLOBAL_SETTINGS.CRITICAL_MARGIN] || 30;

            if (pct >= target) return 'target';     // Green
            if (pct >= critical) return 'warning'; // Yellow
            return 'critical';                     // Red
        },

        selectDeal: async function (guid) {
            const F = window.SCHEMA.FIELDS.DEALS;
            const deal = this.state.deals.find(d => d[F.DEALID] === guid);
            if (!deal) return;

            // 1. Reset state for the new deal
            this.state.selectedDealId = guid;
            this.state.uploadedDocs = [];
            this.state.history = [];
            this.state.isLoadingDocs = true;

            // REQ: If Exception requested, default reviewer decision to 'Reject' (false)
            this.state.feedback = {
                decision: null,
                notes: "",
                actionSummary: "",
                exceptionApproved: deal[F.EXCEPTION_REQ] ? false : null
            };

            // 2. Re-render instantly to show the loading spinner
            this.renderDealDetails();
            this.renderTabs();

            const spId = deal[F.EXTERNALKEY];

            // 3. Fetch Documents & History concurrently
            try {
                const [docsResponse] = await Promise.allSettled([
                    window.SubmissionService.loadDocumentsViaFlow(spId),
                    this.loadReviewHistory(spId)
                ]);

                if (docsResponse.status === 'fulfilled') {
                    this.state.uploadedDocs = docsResponse.value;

                    // REQ 5a: Lazy Update Readiness Score using SubmissionCalc
                    const newStats = window.SubmissionCalc.getGlobalProgress(deal, this.state.uploadedDocs);
                    deal.readinessScore = newStats.percent;
                }
            } catch (e) {
                console.error("Failed to load documents or history", e);
            }

            // 4. Turn off spinner and re-render with actual data
            this.state.isLoadingDocs = false;
            this.renderDealDetails();
        },

        loadReviewHistory: async function (spId) {
            try {
                const url = window.SCHEMA.ENDPOINTS.GET_REVIEW_HISTORY;
                const res = await fetch(url, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ dealId: String(spId) })
                });

                if (res.ok) {
                    const data = await res.json();
                    const F = window.SCHEMA.FIELDS.REVIEW_HISTORY;

                    this.state.history = data.map(item => ({
                        [F.ID]: item.ID,
                        [F.DECISION]: item.ReviewDecision, 
                        [F.NOTES]: item.ReviewNotes,
                        [F.ACTION]: item.ActionRequiredSummary,
                        [F.DATE]: item.Created
                    })).sort((a, b) => new Date(b[F.DATE]) - new Date(a[F.DATE]));

                    this.renderDealDetails();
                }
            } catch (e) {
                console.error("Flow History Load Failed:", e);
            }
        },

        /* =========================================================
           4. UI RENDERERS
           ========================================================= */
        renderLayout: function () {
            const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });

            var html = `
                <header class="bg-white border-b" style="border-color: var(--border-default); position: relative; z-index: 10; width: 100%;">
                    <div style="max-width: 1600px; margin: 0 auto; padding: 0 48px; width: 100%;">
                        <div class="py-6 d-flex align-items-center justify-content-between" style="width: 100%;">
                            
                            <div class="header-title-group">
                                <a href="javascript:void(0);" id="btn-back-dashboard" class="d-inline-flex align-items-center mb-1 text-muted text-decoration-none" style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; gap: 5px;">
                                    <i class="fa fa-arrow-left"></i> Back to Dashboard
                                </a>
                                <h1 class="text-2xl font-bold mb-1" style="color: var(--text-primary); margin: 0; line-height: 1.2;">
                                    Deal Review Board
                                </h1>
                                <p class="text-sm text-muted mb-0" style="font-weight: 500;">
                                    Governance Review & Approval Workflow
                                </p>
                            </div>
                            
                            <div class="header-actions d-flex align-items-center gap-4">
                                <div class="text-muted text-sm font-medium d-flex align-items-center gap-2">
                                    <i class="fa fa-calendar"></i> ${today}
                                </div>
                            </div>
                        </div>
                    </div>
                </header>

                <div class="bg-white border-b" style="border-color: var(--border-default); width: 100%;">
                     <div style="max-width: 1600px; margin: 0 auto; padding: 16px 48px;">
                         <div class="d-flex align-items-center gap-3">
                            <span id="ui-review-count" class="text-xs font-bold text-muted uppercase letter-spacing-1">
                                TODAY'S REVIEWS (${this.state.deals.length})
                            </span>
                            <div class="d-flex gap-2" id="deal-tabs-container"></div>
                        </div>
                     </div>
                </div>

                <main style="max-width: 1600px; margin: 0 auto; padding: 32px 48px;" id="review-main-content"></main>
            `;
            $('#review-board-app-wrapper').html(html);
            this.renderTabs();
        },

        renderTabs: function () {
            const F = window.SCHEMA.FIELDS.DEALS;
            const html = this.state.deals.map(d => {
                const isActive = d[F.DEALID] === this.state.selectedDealId;
                const title = d[F.TITLE] || 'Untitled Deal';
                const spId = d[F.EXTERNALKEY];
                return `
                    <button class="dr-tab-pill ${isActive ? 'is-active' : ''}" data-id="${d[F.DEALID]}">
                        DL-2026-${spId} - ${title}
                    </button>
                `;
            }).join('');
            $('#deal-tabs-container').html(html);
        },

        renderEmptyState: function () {
            $('#review-main-content').html(`
                <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 50vh; text-align: center;">
                    <div class="mb-4" style="font-size: 72px; color: #1E7E34;">
                        <i class="fa fa-check-circle"></i>
                    </div>
                    <h2 class="dr-h2" style="font-size: 36px; margin-bottom: 12px;">You're all caught up!</h2>
                    <p class="dr-sub" style="font-size: 18px;">There are no deals currently pending review.</p>
                </div>
            `);
        },

        renderSkeletons: function() {
            const reviewSkeletons = Array(5).fill(0).map(() => `
                <div class="submission-card" style="padding: 20px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center;">
                    <div style="flex-grow: 1; margin-right: 24px;">
                        <div class="d-flex align-items-center gap-3 mb-2">
                            <div class="shimmer" style="width: 60px; height: 20px; border-radius: 4px;"></div>
                            <div class="shimmer" style="width: 40px; height: 40px; border-radius: 50%;"></div>
                        </div>
                        <div class="shimmer" style="width: 40%; height: 24px; margin-bottom: 8px;"></div>
                        <div class="shimmer" style="width: 20%; height: 14px;"></div>
                    </div>
                    <div style="width: 200px;">
                        <div class="shimmer" style="width: 100%; height: 48px; border-radius: 8px;"></div>
                    </div>
                </div>
            `).join('');
            $('#review-list-container').html(reviewSkeletons);
        },

        renderDocList: function () {
            if (this.state.isLoadingDocs) return `<div class="text-center p-4"><i class="fa fa-spinner fa-spin text-muted mb-2"></i><p class="text-xs">Locating documents...</p></div>`;

            const F = window.SCHEMA.FIELDS.DEALS;
            const deal = this.state.deals.find(d => d[F.DEALID] === this.state.selectedDealId);
            if (!deal) return "";

            // 1. DYNAMIC CATEGORIES: Pull required categories strictly from SubmissionCalc Matrix interpreter
            const requiredCats = window.SubmissionCalc.getRequiredDocs(deal) || [];

            // HELPER: Wildcard matching function for dynamic category IDs
            const isMatch = (file, catId) => {
                const normalizedTarget = (catId || "").toLowerCase();
                const flowCategory = (file.documentCategory || file.spCategory || file.category || "").toLowerCase();
                const fileName = (file.fileName || file.name || "").toLowerCase();

                const displayToIdMap = {
                    'cost model': 'pricing',
                    'statement of work': 'sow',
                    'master agreement': 'msa'
                };

                if (flowCategory === normalizedTarget || displayToIdMap[flowCategory] === normalizedTarget) return true;

                const mapping = {
                    'sow': ['sow'],
                    'msa': ['msa'],
                    'pricing': ['pricing', 'cost', 'estimate'],
                    'rate': ['rate'],
                    'arch': ['arch', 'diagram']
                };

                if (mapping[normalizedTarget] && mapping[normalizedTarget].some(term => fileName.includes(term))) return true;

                const dynamicTerm = normalizedTarget.split('_')[0]; 
                if (dynamicTerm && dynamicTerm.length > 3 && fileName.includes(dynamicTerm)) return true;

                return false;
            };

            // Helper to render a consistent Governance-style Document Card
            const renderCard = (found, forcedLabel = null) => {
                const fileUrl = found.absoluteUrl || found.link || found.url || found.FileRef || '#';
                const fileName = found.name || found.fileName || found.spCategory || "Untitled Document";
                const version = found.version || found.versionNumber || "1.0";
                const uploader = found.uploadedBy || "System";

                const isAligned = (found.status || "").toLowerCase() === 'aligned';
                const statusColor = isAligned ? '#1E7E34' : '#B45309';
                const statusIcon = isAligned ? 'fa-check-circle' : 'fa-exclamation-triangle';
                const statusLabel = isAligned ? 'ALIGNED' : 'MODIFIED';

                const isExternal = fileUrl.includes('3ci-estimator');
                const docIcon = isExternal ? 'fa-calculator text-info' : 'fa-file-pdf-o';

                // --- AI UI LOGIC ---
                const healthScore = found.healthScore || "Pending";
                let aiTheme = { bg: '#F1F5F9', color: '#475569', icon: 'fa-clock-o', label: 'Pending AI Scan' };
                if (healthScore === "Clean") aiTheme = { bg: '#D1F0D8', color: '#1E7E34', icon: 'fa-check-circle', label: 'Clean' };
                else if (healthScore === "Warning") aiTheme = { bg: '#FEF3C7', color: '#B45309', icon: 'fa-exclamation-triangle', label: 'Warning' };
                else if (healthScore === "Critical Risk") aiTheme = { bg: '#FEE2E2', color: '#B91C1C', icon: 'fa-times-circle', label: 'Critical Risk' };

                const isSow = isMatch(found, 'sow');
                
                const aiBadge = (!isExternal && isSow) ? `
                    <span style="background: ${aiTheme.bg}; color: ${aiTheme.color}; padding: 3px 8px; border-radius: 4px; font-size: 9px; font-weight: 800; text-transform: uppercase;">
                        <i class="fa ${aiTheme.icon} mr-1"></i> AI: ${aiTheme.label}
                    </span>
                ` : '';

                const hasFindings = found.aiFindings && found.aiFindings.trim() !== "" && found.aiFindings.trim().toLowerCase() !== "none";
                const findingsBlock = (hasFindings && !isExternal && isSow) ? `
                    <div class="mt-3 p-3 rounded" style="background: #F8FAFC; border: 1px solid #E2E8F0;">
                        <p class="text-xs font-bold mb-1" style="color: ${aiTheme.color};"><i class="fa ${aiTheme.icon}"></i> AI Findings:</p>
                        <div class="text-xs text-muted mb-2" style="white-space: pre-line; line-height: 1.4;">${found.aiFindings}</div>
                        ${found.repComments ? `
                            <div class="p-2 mt-2 rounded" style="background: #fff; border-left: 3px solid #2563EB;">
                                <p class="text-xs font-bold mb-1" style="color: #2563EB;">Rep Explanation:</p>
                                <p class="text-xs text-muted mb-0" style="white-space: pre-line; line-height: 1.4;">${found.repComments}</p>
                            </div>
                        ` : `<p class="text-xs text-danger mb-0 italic mt-2"><i class="fa fa-exclamation-triangle"></i> No rep acknowledgement provided.</p>`}
                    </div>
                ` : '';

                return `
                <a href="${fileUrl}" target="_blank" class="d-block p-3 mb-3 bg-white text-decoration-none doc-item-hover" 
                   style="border: 1px solid var(--border-default, #E2E8F0); border-radius: 8px; box-shadow: 0 1px 2px rgba(0,0,0,0.05); transition: all 0.2s ease;">
                    
                    <div class="d-flex align-items-start gap-3">
                        <div class="d-flex align-items-center justify-content-center rounded" 
                             style="width: 40px; height: 40px; background: #F1F5F9; flex-shrink: 0;">
                            <i class="fa ${docIcon}" style="font-size: 20px; color: #475569;"></i>
                        </div>
                        
                        <div class="flex-grow-1">
                            <div class="d-flex justify-content-between align-items-start">
                                <h4 class="font-bold mb-1" style="font-size: 14px; color: #2563EB; line-height: 1.3; word-break: break-word;">
                                    ${fileName}
                                </h4>
                                ${forcedLabel ? `<span class="text-xs text-muted font-bold px-2 py-1 bg-light rounded" style="border: 1px solid #E2E8F0;">${forcedLabel}</span>` : ''}
                            </div>
                            
                            <div class="text-xs text-muted mb-3" style="font-weight: 500;">
                                v${version} • ${uploader}
                            </div>
                            
                            <div class="d-flex align-items-center gap-2">
                                <span style="color: ${statusColor}; font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px;">
                                    <i class="fa ${statusIcon} mr-1"></i> ${statusLabel}
                                </span>
                                ${aiBadge}
                            </div>

                            ${findingsBlock}
                        </div>
                    </div>
                </a>`;
            };

            // 1. Render Matrix Required Categories
            let html = requiredCats.map(req => {
                const found = this.state.uploadedDocs.find(d => isMatch(d, req.id) && (d.status || "").toLowerCase() !== 'missing');

                if (found) {
                    return renderCard(found, req.name);
                } else {
                    return `
                    <div class="d-block p-3 mb-3 rounded" style="background: #FEF2F2; border: 1px solid #FCA5A5;">
                        <div class="d-flex align-items-center gap-3">
                            <div class="d-flex align-items-center justify-content-center rounded" 
                                 style="width: 40px; height: 40px; background: #FEE2E2; flex-shrink: 0;">
                                <i class="fa fa-exclamation-circle text-danger" style="font-size: 20px;"></i>
                            </div>
                            <div>
                                <p class="font-bold text-danger mb-1" style="font-size: 14px;">Missing ${req.name}</p>
                                <p class="text-xs text-danger mb-0" style="font-weight: 500;">Required for submission</p>
                            </div>
                        </div>
                    </div>`;
                }
            }).join('');

            // 2. Render Additional Documents
            const extras = this.state.uploadedDocs.filter(d =>
                (d.status || "").toLowerCase() !== 'missing' &&
                !requiredCats.some(r => isMatch(d, r.id))
            );

            if (extras.length > 0) {
                html += `
                    <div class="mt-4 pt-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                        <p class="text-xs font-bold text-muted mb-3 text-uppercase letter-spacing-1">Additional Documents</p>
                        ${extras.map(found => renderCard(found)).join('')}
                    </div>`;
            }

            return html;
        },

        renderDealDetails: function () {
            if (!this.state.selectedDealId) return;

            const F = window.SCHEMA.FIELDS.DEALS;
            const deal = this.state.deals.find(d => d[F.DEALID] === this.state.selectedDealId);
            if (!deal) return;

            // --- Shared UI Components ---
            const statusHtml = window.UIComponents.statusBadge(deal[F.STATUS]);
            const ringStyles = window.UIComponents.readinessStyles(deal.readinessScore);
            const docMeta = window.UIComponents.documentProgress(this.state.uploadedDocs, deal);

            const dealTypeText = Object.keys(window.SCHEMA.CHOICES.DEAL_TYPES).find(k => window.SCHEMA.CHOICES.DEAL_TYPES[k] === deal[F.TYPE]) || "Unknown";
            const commModelText = Object.keys(window.SCHEMA.CHOICES.MODELS).find(k => window.SCHEMA.CHOICES.MODELS[k] === deal[F.COMMERCIAL_MODEL]) || "Unknown";
            const submitDateRaw = deal[F.MODIFIED] || deal.createdon || new Date();
            const submitDate = new Date(submitDateRaw).toLocaleDateString('en-US');

            // --- Dynamic Margin Logic ---
            const marginThemes = {
                target: { label: 'TARGET', color: '#1E7E34', bg: '#D1F0D8' },
                warning: { label: 'WARNING', color: '#B45309', bg: '#FEF3C7' },
                critical: { label: 'CRITICAL', color: '#B91C1C', bg: '#FEE2E2' }
            };
            const margin = marginThemes[deal.marginBand];

            // Format value
            const rawData = deal[F.VALUE] || deal.value || deal.totalValue || deal.Value || "0";
            const cleanNumberString = String(rawData).replace(/[^0-9.-]+/g, "");
            const rawValue = parseFloat(cleanNumberString) || 0;
            const displayValue = rawValue >= 1000000 
                ? `$${(rawValue / 1000000).toFixed(2)}M` 
                : `$${(rawValue / 1000).toFixed(1)}K`;

            const rawTech = Object.keys(window.SCHEMA.CHOICES.RISK_LEVELS).find(k => window.SCHEMA.CHOICES.RISK_LEVELS[k] == deal[F.TECH_RISK]) || deal[F.TECH_RISK] || "LOW";
            const rawRes = Object.keys(window.SCHEMA.CHOICES.RISK_LEVELS).find(k => window.SCHEMA.CHOICES.RISK_LEVELS[k] == deal[F.RESOURCE_RISK]) || deal[F.RESOURCE_RISK] || "LOW";
            const techRisk = String(rawTech).toUpperCase().trim();
            const resRisk = String(rawRes).toUpperCase().trim();

            let overallRiskText = "LOW";
            let riskTheme = { bg: '#D1F0D8', text: '#1E7E34', icon: 'fa-check-circle-o' };

            if ([techRisk, resRisk].includes("HIGH")) {
                overallRiskText = "HIGH";
                riskTheme = { bg: '#FEE2E2', text: '#B91C1C', icon: 'fa-warning' };
            } else if ([techRisk, resRisk].includes("MEDIUM")) {
                overallRiskText = "MEDIUM";
                riskTheme = { bg: '#FEF3C7', text: '#B45309', icon: 'fa-exclamation-circle' };
            }
            const formatRiskLabel = (str) => String(str).charAt(0).toUpperCase() + String(str).slice(1).toLowerCase();

            // Validation logic
            const isRejecting = this.state.feedback.decision === 'reject';
            const isActionMissing = isRejecting && !this.state.feedback.actionSummary.trim();
            const actionBorderColor = isActionMissing ? '#EF4444' : 'var(--border-default, #E2E8F0)';
            const actionBorderWidth = isActionMissing ? '2px' : '1px';
            const isSubmitDisabled = !this.state.feedback.decision || isActionMissing;

            // Exception & History Sub-Components
            const exceptionSectionHtml = deal[F.EXCEPTION_REQ] ? `
                <div class="p-3 mb-4 rounded border" style="background: #FFFBEB; border-color: #FEF3C7;">
                    <div class="d-flex align-items-center gap-2 mb-2">
                        <i class="fa fa-shield text-warning"></i>
                        <span class="text-xs font-bold text-uppercase" style="color: #92400E;">Exception Governance</span>
                    </div>
                    <p class="text-muted" style="font-size: 11px; line-height: 1.4;">This deal requires a policy exception. Select an outcome:</p>
                    <div class="d-flex gap-2">
                        <button class="btn btn-sm flex-grow-1 ${this.state.feedback.exceptionApproved === true ? 'btn-success' : 'btn-outline-secondary'}" id="btn-exc-approve" style="font-size: 10px;">Approve</button>
                        <button class="btn btn-sm flex-grow-1 ${this.state.feedback.exceptionApproved === false ? 'btn-danger' : 'btn-outline-secondary'}" id="btn-exc-reject" style="font-size: 10px;">Reject</button>
                    </div>
                </div>` : '';

            const historyHtml = this.state.history.length === 0
                ? `<p class="text-xs text-muted">No previous review history.</p>`
                : this.state.history.map(h => {
                    const FH = window.SCHEMA.FIELDS.REVIEW_HISTORY;
                    const rawVal = h[FH.DECISION];
                    const decText = (rawVal && typeof rawVal === 'object') ? String(rawVal.Value || "") : String(rawVal || "");

                    let displayLabel = decText.replace(/d$/, '');
                    const isApp = displayLabel.includes("Approve") || decText === "1";

                    return `
                        <div class="mb-3 pb-3 border-b text-xs">
                            <div class="d-flex justify-content-between mb-1">
                                <strong style="color: ${isApp ? '#1E7E34' : '#B91C1C'}">${displayLabel}ed</strong>
                                <span class="text-muted">${new Date(h[FH.DATE]).toLocaleDateString()}</span>
                            </div>
                            <p class="mb-2 italic text-muted">${h[FH.NOTES] || "No review notes provided."}</p>
                            ${h[FH.ACTION] ? `
                                <div class="mt-2 p-2 rounded" style="background: #FEF2F2; border-left: 3px solid #EF4444;">
                                    <p class="mb-0" style="color: #B91C1C; font-weight: 600;"><i class="fa fa-exclamation-triangle mr-1"></i> Action Required:</p>
                                    <p class="mb-0" style="color: #7F1D1D;">${h[FH.ACTION]}</p>
                                </div>
                            ` : ''}
                        </div>`;
                }).join('');

            // --- Columns ---
            const leftColumnHtml = `
                <div class="col-md-4">
                    <div id="card-deal-metadata" class="deal-card-v3 clickable-deal-card" style="height: 100%; cursor: pointer; position: relative; transition: all 0.2s ease;" title="Click to view full deal details">
                        <div style="position: absolute; top: 20px; right: 20px;">
                            <i class="fa fa-external-link text-muted" style="opacity: 0.5;"></i>
                        </div>

                        <div class="section-label mb-3 text-xs font-bold text-muted text-uppercase letter-spacing-1">DEAL METADATA</div>
                        <h3 class="font-bold mb-1" style="font-size: 20px; padding-right: 24px;">${deal[F.TITLE]}</h3>
                        <p class="text-md text-muted mb-1">${deal[F.CLIENT_TEXT]}</p>
                        <p class="text-xs text-muted mb-4">DL-${new Date().getFullYear()}-${deal[F.EXTERNALKEY]}</p>

                        <div class="d-flex align-items-center gap-3 mb-4">
                            ${statusHtml}
                            <div class="text-xs font-medium text-muted d-flex align-items-center gap-2">
                                Readiness: <span style="font-weight:700; color: ${ringStyles.text};">${deal.readinessScore}%</span>
                            </div>
                        </div>

                        <div class="pt-4 mb-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                            <div class="section-label mb-3 text-xs font-bold text-muted text-uppercase letter-spacing-1">FINANCIAL OVERVIEW</div>
                            <p class="text-xs text-muted mb-1">Total Deal Value</p>
                            <p class="text-2xl font-bold mb-3">${displayValue}</p>
                            ${margin ? `
                                <div class="badge-margin-v2 d-inline-flex align-items-center gap-2" style="background:${margin.bg}; color:${margin.color}; padding: 4px 10px; border-radius: 4px;">
                                    <span style="font-size: 10px; font-weight: 700;">${margin.label}</span>
                                    <span style="font-size: 12px; font-weight: 800;">${(deal[F.MARGIN] * 100).toFixed(1)}%</span>
                                </div>` : ''}
                        </div>

                        <div class="pt-4 mb-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                            <div class="section-label mb-3 text-xs font-bold text-muted text-uppercase letter-spacing-1">DEAL STRUCTURE</div>
                            <div class="d-flex justify-content-between mb-2 text-sm"><span class="text-muted">Deal Type</span><span class="font-medium">${dealTypeText}</span></div>
                            <div class="d-flex justify-content-between mb-2 text-sm"><span class="text-muted">Commercial Model</span><span class="font-medium">${commModelText}</span></div>
                            <div class="d-flex justify-content-between mb-2 text-sm"><span class="text-muted">Owner</span><span class="font-medium">${deal[F.SALES_LEADER]?.split('@')[0]}</span></div>
                            <div class="d-flex justify-content-between mb-2 text-sm"><span class="text-muted">Submitted</span><span class="font-medium">${submitDate}</span></div>
                        </div>

                        <div class="pt-4 mb-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                            <div class="section-label mb-3 text-xs font-bold text-muted text-uppercase letter-spacing-1">RISK ASSESSMENT</div>
                            <div class="mb-3">
                                <span class="badge-risk-v2 d-inline-flex align-items-center gap-2" style="background: ${riskTheme.bg}; color: ${riskTheme.text}; padding: 4px 10px; border-radius: 4px; font-size: 10px; font-weight: 700;">
                                    <i class="fa ${riskTheme.icon}"></i> ${overallRiskText} RISK
                                </span>
                            </div>
                            <p class="text-xs font-bold mb-2" style="color: var(--text-secondary);">Key Risk Factors:</p>
                            <ul class="text-xs text-muted pl-3 mb-0" style="list-style-type: disc;">
                                <li style="margin-bottom: 4px;"><strong>Technical:</strong> ${formatRiskLabel(techRisk)} complexity</li>
                                <li style="margin-bottom: 4px;"><strong>Resource:</strong> ${formatRiskLabel(resRisk)} availability risk</li>
                                ${deal[F.EXCEPTION_REQ] ? '<li class="text-danger" style="margin-bottom: 4px;"><strong>Exception:</strong> Non-standard terms requested</li>' : ''}
                            </ul>
                        </div>

                        <div class="pt-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                            <div class="section-label mb-3 text-xs font-bold text-muted text-uppercase letter-spacing-1">DOCUMENTATION</div>
                            <div class="d-flex justify-content-between mb-2 text-sm">
                                <span class="text-muted">Required Documents</span>
                                <span class="font-medium">${docMeta.count}</span>
                            </div>
                            <div class="d-flex justify-content-between mb-2 text-sm">
                                <span class="text-muted">Required Fields</span>
                                <span class="font-medium" style="color: ${deal.readinessScore === 100 ? '#1E7E34' : '#B45309'}">
                                    ${deal.readinessScore === 100 ? 'Complete' : deal.readinessScore + '%'}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            `;

            const centerColumnHtml = `
                <div class="col-md-4">
                    <div class="deal-card-v3" style="height: 100%; background: #F8FAFC;">
                        <div class="section-label mb-4">DEAL DOCUMENTS</div>
                        <div class="bg-white p-4 rounded border mb-4">
                            <p class="text-center font-bold text-sm mb-4">Governance Vault</p>
                            ${this.renderDocList()}
                        </div>
                        <p class="text-center text-xs text-muted">Click on a document above to view it.</p>
                    </div>
                </div>
            `;

            const rightColumnHtml = `
                <div class="col-md-4">
                    <div class="deal-card-v3" style="height: 100%;">
                        <div class="section-label mb-4">DEAL FEEDBACK</div>
                        
                        <div class="d-flex gap-3 mb-4">
                            <button class="btn-decision flex-grow-1 ${this.state.feedback.decision === 'approve' ? 'is-approve' : ''}" data-vote="approve">
                                <i class="fa fa-check-circle"></i> Approve
                            </button>
                            <button class="btn-decision flex-grow-1 ${this.state.feedback.decision === 'reject' ? 'is-reject' : ''}" data-vote="reject">
                                <i class="fa fa-times-circle"></i> Reject
                            </button>
                        </div>

                        ${exceptionSectionHtml}

                        <div class="form-group mb-4">
                            <label class="text-xs font-bold text-muted mb-2 d-block">Review Notes</label>
                            <div id="editor-notes" style="height: 120px; background: #fff; margin-bottom: 24px;">${this.state.feedback.notes}</div>
                            
                            <label class="text-xs font-bold text-muted mb-2 d-block">Action Required Summary</label>
                            <div id="editor-action-container" style="border: ${actionBorderWidth} solid ${actionBorderColor}; border-radius: 4px; transition: all 0.2s;">
                                <div id="editor-action" style="height: 120px; background: #fff;">${this.state.feedback.actionSummary}</div>
                            </div>
                            <p id="action-summary-warning" style="color: #B91C1C; font-size: 10px; font-weight: 700; text-transform: uppercase; margin-top: 4px; display: ${isRejecting && !this.state.feedback.actionSummary.trim() ? 'block' : 'none'};">
                                <i class="fa fa-exclamation-triangle"></i> Mandatory for rejections
                            </p>
                        </div>

                        <button id="btn-submit-review" class="btn-submission btn-submit w-100 mb-4" 
                            ${isSubmitDisabled ? 'disabled' : ''} 
                            style="opacity: ${isSubmitDisabled ? '0.5' : '1'}; justify-content: center;">
                            Record Decision
                        </button>

                        <div class="pt-4" style="border-top: 1px solid var(--border-default, #E2E8F0);">
                            <div class="section-label mb-2">REVIEW HISTORY</div>
                            ${historyHtml}
                        </div>
                    </div>
                </div>
            `;

            $('#review-main-content').html(`<div class="row g-4">${leftColumnHtml}${centerColumnHtml}${rightColumnHtml}</div>`);
            this.initEditors();
        },

        initEditors: function () {
            const self = this;
            const toolbarOptions = [
                ['bold', 'italic', 'underline'],
                [{ 'list': 'ordered' }, { 'list': 'bullet' }],
                ['clean']
            ];

            this.quillNotes = new Quill('#editor-notes', { theme: 'snow', modules: { toolbar: toolbarOptions }, placeholder: 'Enter feedback notes...' });
            this.quillAction = new Quill('#editor-action', { theme: 'snow', modules: { toolbar: toolbarOptions }, placeholder: 'List required actions for resubmission...' });

            this.quillNotes.on('text-change', function () { self.state.feedback.notes = self.quillNotes.root.innerHTML; });

            this.quillAction.on('text-change', function () {
                self.state.feedback.actionSummary = self.quillAction.root.innerHTML;

                const rawText = self.quillAction.getText().trim();
                const isRejecting = self.state.feedback.decision === 'reject';
                const isActionMissing = isRejecting && rawText.length === 0;

                if (isActionMissing) {
                    $('#editor-action-container').css({ 'border-color': '#EF4444', 'border-width': '2px' });
                    $('#action-summary-warning').show();
                } else {
                    $('#editor-action-container').css({ 'border-color': 'var(--border-default, #E2E8F0)', 'border-width': '1px' });
                    $('#action-summary-warning').hide();
                }

                const isSubmitDisabled = !self.state.feedback.decision || isActionMissing;
                $('#btn-submit-review').prop('disabled', isSubmitDisabled).css('opacity', isSubmitDisabled ? '0.5' : '1');
            });
        },

        /* =========================================================
           5. EVENT BINDING
           ========================================================= */
        bindEvents: function () {
            const self = this;

            $(document).off('click', '#btn-back-dashboard').on('click', '#btn-back-dashboard', function () { window.location.href = '/'; });
            $(document).off('click', '.dr-tab-pill').on('click', '.dr-tab-pill', function () { self.selectDeal($(this).data('id')); });

            $(document).off('click', '.btn-decision').on('click', '.btn-decision', function () {
                self.state.feedback.decision = $(this).data('vote');
                self.renderDealDetails();
            });

            $(document).off('click', '#btn-exc-approve').on('click', '#btn-exc-approve', function () {
                self.state.feedback.exceptionApproved = true;
                self.renderDealDetails();
            });
            $(document).off('click', '#btn-exc-reject').on('click', '#btn-exc-reject', function () {
                self.state.feedback.exceptionApproved = false;
                self.renderDealDetails();
            });

            $(document).off('click', '#btn-submit-review').on('click', '#btn-submit-review', async function () {
                const decision = self.state.feedback.decision;
                if (!decision) return;

                const F = window.SCHEMA.FIELDS.DEALS;
                const C = window.SCHEMA.CHOICES.STATUS;
                const deal = self.state.deals.find(d => d[F.DEALID] === self.state.selectedDealId);

                if (decision === 'reject' && !self.state.feedback.actionSummary.trim()) {
                    alert("Validation Error: An 'Action Required Summary' is mandatory when rejecting.");
                    return;
                }

                const $btn = $(this);
                $btn.html('<i class="fa fa-spinner fa-spin"></i> Recording...').prop('disabled', true);

                try {
                    const updateData = {
                        [F.STATUS]: decision === 'approve' ? C.APPROVED : C.REJECTED,
                        [F.REVIEW_NOTES]: self.state.feedback.notes || "",
                        [F.ACTION_REQUIRED]: self.state.feedback.actionSummary || ""
                    };
                    if (deal[F.EXCEPTION_REQ]) updateData[F.EXCEPTION_APP] = self.state.feedback.exceptionApproved;

                    const auditPayload = {
                        dealId: String(deal[F.EXTERNALKEY]),
                        decision: decision === 'approve' ? "Approve" : "Reject",
                        notes: self.state.feedback.notes,
                        actionSummary: self.state.feedback.actionSummary,
                        reviewer: window.USER_CONTEXT?.fullname || "Review Board"
                    };

                    const [dvSuccess] = await Promise.all([
                        window.SubmissionService.patchDeal(self.state.selectedDealId, updateData),
                        fetch(window.SCHEMA.ENDPOINTS.RECORD_REVIEW_DECISION, {
                            method: 'POST',
                            headers: { 'Content-Type': 'application/json' },
                            body: JSON.stringify(auditPayload)
                        })
                    ]);

                    if (dvSuccess) {
                        const completedDealId = self.state.selectedDealId;
                        self.state.deals = self.state.deals.filter(d => d[F.DEALID] !== self.state.selectedDealId);
                        $('#ui-review-count').text(`TODAY'S REVIEWS (${self.state.deals.length})`);

                        if (self.state.deals.length > 0) {
                            await self.selectDeal(self.state.deals[0][F.DEALID]);
                        } else {
                            self.state.selectedDealId = null;
                            self.renderEmptyState();
                            $('#deal-tabs-container').empty();
                        }
                        
                        window.ImpactTracker.showModal(completedDealId, decision);
                    }
                } catch (e) {
                    console.error("Submission Error:", e);
                    alert("Failed to record decision. Please try again.");
                    $btn.html('Record Decision').prop('disabled', false);
                }
            });
        }
    };

    window.ReviewBoardApp = ReviewBoardApp;

    $(document).ready(() => {
        const checkDependencies = setInterval(() => {
            if (window.SCHEMA && window.UIComponents && window.SubmissionCalc && window.SubmissionService) {
                clearInterval(checkDependencies);
                ReviewBoardApp.init();
            }
        }, 50);
    });

})(jQuery);